### ISSUE TITLE
Not mobile-ready

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/ai-coloring-book#9]
Deployed changes to <https://susieqsbooks.org/|https://susieqsbooks.org/> 

Noticed that this doesn't render very well on mobile, will likely be the last thing we need to fix before we call this done <!subteam^S06220M9LFQ|@team-susieq-kids>

[Slack Message](https://opportunity-hack.slack.com/archives/C060642JYP4/p1708566758612009)

**Comment by dashk11** [comment]
Added fix under testing
